require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'


spec = Gem::Specification.new do |s| 
  s.name = "dss_client"
  s.version = "0.0.1"
  s.author = "Dave Garcia"
  s.email = "david.garcia@tractis.com"
  s.platform = Gem::Platform::RUBY
  s.summary = "Allows ruby applications to request digital signature services based on OASIS Dss protocol"
  s.files = FileList["{lib}/**/*"].to_a
  s.require_path = "lib"
  s.autorequire = "name"
  s.test_files = FileList["{test}/**/*test.rb"].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ["README"]
end
 
Rake::GemPackageTask.new(spec) do |pkg| 
  pkg.need_tar = true 
end 



def test_suite_cmdline
  require 'find'
  files = []
  Find.find("test") do |f|
    files << f if File.basename(f) =~ /.*test.*\.rb$/
  end

  Find.find("src") do |f|
    files << f if File.basename(f) =~ /.*\.rb$/
  end

  puts "Files are #{files}"

  cmdline = "ruby -w -I.:lib:ext:test -rtest/unit -e '%w[#{files.join(' ')}].each {|f| require f}'"
end


desc "Testing library DSS pure ruby"
task :units do
    cmdline = "#{test_suite_cmdline}"
    puts cmdline
    system cmdline
end

task :test => [:units ]
task :default => [:gem]
